"""Додано використання каскадів та loads

Revision ID: 0570cc02783f
Revises: a43b781db51b
Create Date: 2024-12-23 14:48:03.674530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0570cc02783f'
down_revision = 'a43b781db51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Unicode(length=40),
               type_=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
