"""Поєднана таблиця

Revision ID: 1334e8062467
Revises: 961f6a6f21ea
Create Date: 2024-12-24 23:00:34.661807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1334e8062467'
down_revision = '961f6a6f21ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('user_records', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_records_record_id_records'), 'records', ['record_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_records_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_records_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_records_record_id_records'), type_='foreignkey')

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61387C714A')
    )
    # ### end Alembic commands ###
