"""Змінений тип даних у id музики

Revision ID: 66bd6ba5758c
Revises: 860a1b353682
Create Date: 2024-12-20 20:52:51.686318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bd6ba5758c'
down_revision = '860a1b353682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musicians', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musicians', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=80, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))

    # ### end Alembic commands ###
