"""Змінена назва таблиці reaction

Revision ID: 6ed3e7cc0073
Revises: 79f387be70ce
Create Date: 2024-12-25 21:05:40.326365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed3e7cc0073'
down_revision = '79f387be70ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reaction_types'))
    )
    with op.batch_alter_table('reaction_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reaction_types_name'), ['name'], unique=True)

    op.drop_table('reactions')
    with op.batch_alter_table('user_musician_reactions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_musician_reactions_reaction_id_reaction_types'), 'reaction_types', ['reaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_musician_reactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_musician_reactions_reaction_id_reaction_types'), type_='foreignkey')

    op.create_table('reactions',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_reactions')
    )
    with op.batch_alter_table('reaction_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reaction_types_name'))

    op.drop_table('reaction_types')
    # ### end Alembic commands ###
