"""userrecord ініціалізовано на рівні

Revision ID: 90b5ee9c65ca
Revises: 9cd8cc276daa
Create Date: 2024-12-24 14:30:42.426092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b5ee9c65ca'
down_revision = '9cd8cc276daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_records', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_records_record_id_records'), 'records', ['record_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_records_record_id_records'), type_='foreignkey')

    # ### end Alembic commands ###
