"""empty message

Revision ID: 92c944eecd8e
Revises: f2f0da17ec74
Create Date: 2024-12-25 21:33:53.460898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c944eecd8e'
down_revision = 'f2f0da17ec74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_musician_reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reaction_type_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_user_musician_reactions_reaction_id_reaction_types', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_musician_reactions_reaction_type_id_reaction_types'), 'reaction_types', ['reaction_type_id'], ['id'])
        batch_op.drop_column('reaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_musician_reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reaction_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_user_musician_reactions_reaction_type_id_reaction_types'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_musician_reactions_reaction_id_reaction_types', 'reaction_types', ['reaction_id'], ['id'])
        batch_op.drop_column('reaction_type_id')

    # ### end Alembic commands ###
