"""empty message

Revision ID: 955d4d269d3f
Revises: 90b5ee9c65ca
Create Date: 2024-12-24 14:39:56.921045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '955d4d269d3f'
down_revision = '90b5ee9c65ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('user_records', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_records_record_id_records'), 'records', ['record_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_records_record_id_records'), type_='foreignkey')
        batch_op.alter_column('rating',
               existing_type=sa.Float(precision=2),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61093CFE92')
    )
    # ### end Alembic commands ###
