"""empty message

Revision ID: 9af45f03696f
Revises: 54d55a6ec25e
Create Date: 2024-12-25 21:51:51.089895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af45f03696f'
down_revision = '54d55a6ec25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_records', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
