"""changed represantation of userRecord table

Revision ID: 9cd8cc276daa
Revises: 1aca4022dd49
Create Date: 2024-12-24 14:22:46.443885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '9cd8cc276daa'
down_revision = '1aca4022dd49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('user_records', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_records', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B615E730E11')
    )
    # ### end Alembic commands ###
