"""autoincrement

Revision ID: 9f38942c6d46
Revises: 
Create Date: 2024-12-23 03:31:54.988688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '9f38942c6d46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('user_musician_reactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_musician_reactions_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_musician_reactions_musician_id_musicians'), 'musicians', ['musician_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_musician_reactions_reaction_id_reactions'), 'reactions', ['reaction_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_musician_reactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_musician_reactions_reaction_id_reactions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_musician_reactions_musician_id_musicians'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_musician_reactions_user_id_users'), type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61861A809A')
    )
    # ### end Alembic commands ###
