"""Незначні покращення

Revision ID: ba1fe3754f02
Revises: 0570cc02783f
Create Date: 2024-12-23 15:04:18.535889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1fe3754f02'
down_revision = '0570cc02783f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aliases_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aliases_id'))

    # ### end Alembic commands ###
