"""складний первинний ключ був доданий до userrecords таблицю

Revision ID: bbc6c4c49002
Revises: e23dfa5edc23
Create Date: 2024-12-24 01:35:50.122374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'bbc6c4c49002'
down_revision = 'e23dfa5edc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_records',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name=op.f('fk_user_records_record_id_records')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_records_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'record_id', name=op.f('pk_user_records'))
    )
    op.drop_table('sysdiagrams')
    op.drop_table('userrecords')
    with op.batch_alter_table('musicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_musicians_name'), ['name'], unique=False)

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reactions_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reactions_name'))

    with op.batch_alter_table('musicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_musicians_name'))

    op.create_table('userrecords',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('rating', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name='fk_userrecords_record_id_records'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_userrecords_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_userrecords')
    )
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B617300AE2A')
    )
    op.drop_table('user_records')
    # ### end Alembic commands ###
