"""нова табличка для збільшення взаємодії користувача

Revision ID: e23dfa5edc23
Revises: 22c570eaaee2
Create Date: 2024-12-24 00:30:54.193346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'e23dfa5edc23'
down_revision = '22c570eaaee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userrecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name=op.f('fk_userrecords_record_id_records')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_userrecords_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userrecords'))
    )
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('musicians', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=40),
               existing_nullable=False)

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('musicians', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Unicode(length=40),
               type_=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61FEF96CD4')
    )
    op.drop_table('userrecords')
    # ### end Alembic commands ###
